AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Service Template for Application Module

Parameters:
  EnvironmentName:
    Description: Environment name (staging or production)
    Type: String
    AllowedValues:
      - staging
      - production
    Default: staging

  ServiceName:
    Description: Name of the ECS service
    Type: String
    Default: module-1

  ContainerPort:
    Description: Port exposed by the container
    Type: Number
    Default: 8080

  DesiredCount:
    Description: Number of desired tasks
    Type: Number
    Default: 2

  CPU:
    Description: CPU units for the task (256, 512, 1024, 2048, 4096)
    Type: Number
    Default: 256
    AllowedValues:
      - 256
      - 512
      - 1024
      - 2048
      - 4096

  Memory:
    Description: Memory for the task in MB
    Type: Number
    Default: 512
    AllowedValues:
      - 512
      - 1024
      - 2048
      - 4096
      - 8192

  ImageUri:
    Description: Container image URI (ECR repository URI with tag)
    Type: String
    Default: 'PLACEHOLDER_IMAGE_URI:latest'

  HealthCheckPath:
    Description: Health check path for the container
    Type: String
    Default: /health

  TargetGroupArn:
    Description: ARN of the ALB target group
    Type: String

Conditions:
  IsProduction: !Equals [!Ref EnvironmentName, 'production']

Resources:
  # Task Definition
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${EnvironmentName}-${ServiceName}
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref CPU
      Memory: !Ref Memory
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${EnvironmentName}-ECSTaskExecutionRoleArn
      TaskRoleArn:
        Fn::ImportValue: !Sub ${EnvironmentName}-ECSTaskRoleArn
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Image: !Ref ImageUri
          Essential: true
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              Protocol: tcp
          Environment:
            - Name: ENVIRONMENT
              Value: !Ref EnvironmentName
            - Name: SERVICE_NAME
              Value: !Ref ServiceName
            - Name: PORT
              Value: !Ref ContainerPort
            - Name: DATABASE_HOST
              Value:
                Fn::ImportValue: !Sub ${EnvironmentName}-DBEndpoint
            - Name: DATABASE_PORT
              Value:
                Fn::ImportValue: !Sub ${EnvironmentName}-DBPort
            - Name: REDIS_HOST
              Value:
                Fn::ImportValue: !Sub ${EnvironmentName}-CacheEndpoint
            - Name: REDIS_PORT
              Value:
                Fn::ImportValue: !Sub ${EnvironmentName}-CachePort
          Secrets:
            - Name: DATABASE_PASSWORD
              ValueFrom: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${EnvironmentName}/database-password
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Fn::ImportValue: !Sub ${EnvironmentName}-ECSLogGroupName
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Ref ServiceName
          HealthCheck:
            Command:
              - CMD-SHELL
              - !Sub 'curl -f http://localhost:${ContainerPort}${HealthCheckPath} || exit 1'
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-${ServiceName}-task
        - Key: Environment
          Value: !Ref EnvironmentName

  # ECS Service
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub ${EnvironmentName}-${ServiceName}
      Cluster:
        Fn::ImportValue: !Sub ${EnvironmentName}-ECSClusterName
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue: !Sub ${EnvironmentName}-ECSSecurityGroupId
          Subnets:
            - Fn::ImportValue: !Sub ${EnvironmentName}-PrivateSubnet1Id
            - Fn::ImportValue: !Sub ${EnvironmentName}-PrivateSubnet2Id
      LoadBalancers:
        - ContainerName: !Ref ServiceName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroupArn
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: !If [IsProduction, 100, 50]
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      EnableExecuteCommand: true
      HealthCheckGracePeriodSeconds: 60
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-${ServiceName}
        - Key: Environment
          Value: !Ref EnvironmentName

  # Auto Scaling Target
  AutoScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: !If [IsProduction, 10, 4]
      MinCapacity: !If [IsProduction, 2, 1]
      ResourceId: !Sub service/${EnvironmentName}-cluster/${EnvironmentName}-${ServiceName}
      RoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
    DependsOn: Service

  # CPU-based Auto Scaling Policy
  CPUScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub ${EnvironmentName}-${ServiceName}-cpu-scaling
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref AutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        TargetValue: 70.0
        ScaleInCooldown: 300
        ScaleOutCooldown: 60

  # Memory-based Auto Scaling Policy
  MemoryScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub ${EnvironmentName}-${ServiceName}-memory-scaling
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref AutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageMemoryUtilization
        TargetValue: 80.0
        ScaleInCooldown: 300
        ScaleOutCooldown: 60

Outputs:
  ServiceName:
    Description: ECS Service Name
    Value: !GetAtt Service.Name

  ServiceArn:
    Description: ECS Service ARN
    Value: !Ref Service

  TaskDefinitionArn:
    Description: Task Definition ARN
    Value: !Ref TaskDefinition
