AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer for Multi-Module Application

Parameters:
  EnvironmentName:
    Description: Environment name (staging or production)
    Type: String
    AllowedValues:
      - staging
      - production
    Default: staging

  CertificateArn:
    Description: ARN of the SSL certificate (optional, leave empty for HTTP only)
    Type: String
    Default: ''

  Module1Port:
    Description: Port for Module 1
    Type: Number
    Default: 8081

  Module2Port:
    Description: Port for Module 2
    Type: Number
    Default: 8082

  Module3Port:
    Description: Port for Module 3
    Type: Number
    Default: 8083

  Module4Port:
    Description: Port for Module 4
    Type: Number
    Default: 8084

Conditions:
  HasCertificate: !Not [!Equals [!Ref CertificateArn, '']]
  IsProduction: !Equals [!Ref EnvironmentName, 'production']

Resources:
  # Application Load Balancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${EnvironmentName}-alb
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      SecurityGroups:
        - Fn::ImportValue: !Sub ${EnvironmentName}-ALBSecurityGroupId
      Subnets:
        - Fn::ImportValue: !Sub ${EnvironmentName}-PublicSubnet1Id
        - Fn::ImportValue: !Sub ${EnvironmentName}-PublicSubnet2Id
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'
        - Key: routing.http.drop_invalid_header_fields.enabled
          Value: 'true'
        - Key: deletion_protection.enabled
          Value: !If [IsProduction, 'true', 'false']
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-alb
        - Key: Environment
          Value: !Ref EnvironmentName

  # HTTP Listener (redirects to HTTPS if certificate exists)
  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - !If
          - HasCertificate
          - Type: redirect
            RedirectConfig:
              Protocol: HTTPS
              Port: '443'
              StatusCode: HTTP_301
          - Type: forward
            TargetGroupArn: !Ref Module1TargetGroup

  # HTTPS Listener (only created if certificate provided)
  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: HasCertificate
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref Module1TargetGroup

  # Target Groups for each module
  Module1TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-module-1-tg
      VpcId:
        Fn::ImportValue: !Sub ${EnvironmentName}-VpcId
      Port: !Ref Module1Port
      Protocol: HTTP
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: 200-299
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '30'
        - Key: stickiness.enabled
          Value: 'false'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-module-1-tg
        - Key: Environment
          Value: !Ref EnvironmentName

  Module2TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-module-2-tg
      VpcId:
        Fn::ImportValue: !Sub ${EnvironmentName}-VpcId
      Port: !Ref Module2Port
      Protocol: HTTP
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: 200-299
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '30'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-module-2-tg
        - Key: Environment
          Value: !Ref EnvironmentName

  Module3TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-module-3-tg
      VpcId:
        Fn::ImportValue: !Sub ${EnvironmentName}-VpcId
      Port: !Ref Module3Port
      Protocol: HTTP
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: 200-299
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '30'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-module-3-tg
        - Key: Environment
          Value: !Ref EnvironmentName

  Module4TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-module-4-tg
      VpcId:
        Fn::ImportValue: !Sub ${EnvironmentName}-VpcId
      Port: !Ref Module4Port
      Protocol: HTTP
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: 200-299
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '30'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-module-4-tg
        - Key: Environment
          Value: !Ref EnvironmentName

  # Listener Rules for path-based routing
  Module2ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !If [HasCertificate, !Ref HTTPSListener, !Ref HTTPListener]
      Priority: 10
      Conditions:
        - Field: path-pattern
          Values:
            - /api/module2/*
            - /module2/*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref Module2TargetGroup

  Module3ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !If [HasCertificate, !Ref HTTPSListener, !Ref HTTPListener]
      Priority: 20
      Conditions:
        - Field: path-pattern
          Values:
            - /api/module3/*
            - /module3/*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref Module3TargetGroup

  Module4ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !If [HasCertificate, !Ref HTTPSListener, !Ref HTTPListener]
      Priority: 30
      Conditions:
        - Field: path-pattern
          Values:
            - /api/module4/*
            - /module4/*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref Module4TargetGroup

Outputs:
  LoadBalancerDNSName:
    Description: DNS name of the load balancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub ${EnvironmentName}-ALBDNSName

  LoadBalancerArn:
    Description: ARN of the load balancer
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: !Sub ${EnvironmentName}-ALBArn

  LoadBalancerFullName:
    Description: Full name of the load balancer for CloudWatch metrics
    Value: !GetAtt ApplicationLoadBalancer.LoadBalancerFullName
    Export:
      Name: !Sub ${EnvironmentName}-ALBFullName

  LoadBalancerHostedZoneId:
    Description: Hosted zone ID of the load balancer
    Value: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
    Export:
      Name: !Sub ${EnvironmentName}-ALBHostedZoneId

  Module1TargetGroupArn:
    Description: ARN of Module 1 target group
    Value: !Ref Module1TargetGroup
    Export:
      Name: !Sub ${EnvironmentName}-Module1TargetGroupArn

  Module2TargetGroupArn:
    Description: ARN of Module 2 target group
    Value: !Ref Module2TargetGroup
    Export:
      Name: !Sub ${EnvironmentName}-Module2TargetGroupArn

  Module3TargetGroupArn:
    Description: ARN of Module 3 target group
    Value: !Ref Module3TargetGroup
    Export:
      Name: !Sub ${EnvironmentName}-Module3TargetGroupArn

  Module4TargetGroupArn:
    Description: ARN of Module 4 target group
    Value: !Ref Module4TargetGroup
    Export:
      Name: !Sub ${EnvironmentName}-Module4TargetGroupArn

  HTTPListenerArn:
    Description: ARN of HTTP listener
    Value: !Ref HTTPListener
    Export:
      Name: !Sub ${EnvironmentName}-HTTPListenerArn

  HTTPSListenerArn:
    Description: ARN of HTTPS listener
    Condition: HasCertificate
    Value: !Ref HTTPSListener
    Export:
      Name: !Sub ${EnvironmentName}-HTTPSListenerArn
